name: develop

on:
  push:
    branches:
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Add GitHub Nuget Source
      run: dotnet nuget add source https://nuget.pkg.github.com/anyways-open/index.json -n anyways -u xivk -p ${{secrets.PACKAGES_SECRET }} --store-password-in-clear-text
    
    - name: Add GitHub Nuget Source
      run: dotnet nuget add source https://nuget.pkg.github.com/itinero/index.json -n itinero -u xivk -p ${{secrets.PACKAGES_SECRET }} --store-password-in-clear-text
    
    - name: Add GitHub Nuget Source
      run: dotnet nuget add source https://nuget.pkg.github.com/osmsharp/index.json -n osmsharp -u xivk -p ${{secrets.PACKAGES_SECRET }} --store-password-in-clear-text

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal  

    - name: Run dotnet format
      run: dotnet format --verify-no-changes --verbosity diagnostic --no-restore

    - name: Nuget Pack
      run: dotnet pack -c release
      working-directory: ./src/Itinero.Transit/
    - name: Nuget Pack
      run: dotnet pack -c release
      working-directory: ./src/Itinero.Transit.IO.LC/
    - name: Nuget Pack
      run: dotnet pack -c release
      working-directory: ./src/Itinero.Transit.IO.OSM/

    - name: Nuget Push
      run: dotnet nuget push **/*.nupkg --skip-duplicate -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/anyways-open/index.json
      working-directory: ./src/
